### PR TITLE
RSS-related fixes

### PR DESCRIPTION
**Pull request by maleadt**

### CODE REVIEW

**Comment by maleadt** [comment]
I see you've caught some of these fixes already, I'll remove them here.

**Comment by tlienart** [comment]
Thanks a lot for this, adding some thoughts for the eventual completion of the work on my side:

- full content has an ambiguity for {{..}} function in terms of how they should be inserted
- the description should be plain text if there's content (though actually it looks like no one knows), there's no function to go from markdown to plain text at the moment

**Comment by tlienart** [comment]
This is a very good point and I had not thought about it, thanks! I need to mull over this a bit and hopefully something nice will come out 😄

**Comment by tlienart** [comment]
closing this as changes are now pending on #799, thanks Tim

**Pull request closed without merging**
