### PR TITLE
draft PR for fr818

### PR DESCRIPTION
**Pull request by tlienart**

### CODE REVIEW

**Comment by kescobo** [comment]
This is super helpful, thanks for getting me started!

**Comment by kescobo** [comment]
@tlienart Is there a straightforward way to isolate and test `resolve_code_block()`?

I tried 

````
julia> replcode = """
       ```julia
       foo = 2+2
       bar = foo + 3
       ```"""
"```julia\nfoo = 2+2\nbar = foo + 3\n```"

julia> Franklin.resolve_code_block(SubString(replcode), repl=true)
"<pre><code class=\"language-julia\">foo &#61; 2&#43;2\nbar &#61; foo &#43; 3</code></pre>"
````

but this hits `isnothing(rpath) && return html_code(code, lang)` and returns. Putting a block into an existing site and using `serve()` to throw the error is a bit challenging.

**Comment by tlienart** [comment]
Set shortcut=true, repl would never be true without shortcut being as well

**Comment by kescobo** [comment]
`shortcut = true` throws TypeError from `lang  = locvar(:lang)::String`...

**Comment by tlienart** [comment]
use `Franklin.set_var!(Franklin.LOCAL_VARS, "lang", "julia")`

**Comment by tlienart** [comment]
hello @kescobo do you need any help with this?

**Comment by kescobo** [comment]
@tlienart I haven't had much opportunity to work on it in the past couple of weeks, sorry 😐. I got stuck trying to test a function, but haven't had time to try your latest suggestion - hoping to return to it next week, but if it's a quick fix on your end, I won't be bothered of you take it over.

**Comment by tlienart** [comment]
no worries, I'm keen for external users to try stuff for feature requests like this one and was just offering to unblock you if you had time to push this, there's no rush in any case :)

**Comment by kescobo** [comment]
Sorry this has languished so long. I am still planning to work on this - but I don't want to be a [cookie licker](https://communitymgt.fandom.com/wiki/Cookie_Licking)... If you or someone else wants this, totally fine with me to take it.

**Comment by tlienart** [comment]
No worries @kescobo, you're the only person who's asked for this and while I support the idea and will help you push it through, I don't think someone else will :-)

**Comment by tlienart** [comment]
Just a note and a ref that Shashi Gowda had a go at it: https://github.com/JuliaSymbolics/Symbolics.jl/pull/527 and it's looking great!

**Comment by gdalle** [comment]
Bumping to say that I strongly support this idea, it's very useful for introductory Julia blog posts like the one I'm writing with @jacobussmit

**Comment by tlienart** [comment]
finally had a stab at this, see #1035 ; kindly try it there, if it seems to work well for you I'll merge it and add it as a patch release (even though it's kind of a new feature but I had told myself I wouldn't do a minor release until the upcoming big one so this would be a bit of an exception)

**Pull request closed without merging**
