### PR TITLE
Make `div_content` settable from a page

### LINKED ISSUE #983: Unable to set `div_content` with local page variable
According to the docs, the global page variable `div_content` should be overwritten if set as local page variable, but this does not happen.

I'm guessing this can easily be fixed by using `locvar` instead of `globvar` in the `build_page` method on [src/manager/write_page.jl](../blob/6f24bef91a256731ca7a3609e4b777fe71594200/src/manager/write_page.jl)

The new `content_class` variable does also not support setting it from a local page.

### PR DESCRIPTION
**Pull request by stanvanlier**
Fixes #983

### CODE REVIEW

**Comment by tlienart** [comment]
Thanks!!

**Comment by tlienart** [comment]
Ps: do you need a patch release with this or are you ok to work with master for now?

**Comment by stanvanlier** [comment]
Yes would like to deploy using gitlab ci, or is that also possible with master?

**Comment by tlienart** [comment]
It is, the only difference is that in the gitlab script you'll have to install a specific version with something like

```
using Pkg
Pkg.add(PackageSpec(name="Franklin", rev="master"))
using Franklin
Franklin.optimize(...)
```

as opposed to just putting Franklin in the Project toml.

Happy to do a patch release as well, might do that within 24h anyway

**Comment by stanvanlier** [comment]
Ah ok thanks! I'll use master for now then

**Pull request merged**
