### PR TITLE
Omit index.html from URLs in feed.xml.

### PR DESCRIPTION
**Pull request by fredrikekre**
Is this OK or does it have to include `index.html`? I could not find anything online.

### CODE REVIEW

**Comment by fredrikekre** [comment]
I guess the same could be done for `sitemap.xml`?

**Comment by tlienart** [comment]
I can't imagine it's necessary (though, like you, I didn't know and went for the conservative route but that's probably not needed), I'll merge this without releasing,  test it a bit with a couple of RSS readers and we can revert if there's something fishy going on.

Thanks for all the contribs!

**Comment by fredrikekre** [comment]
On second though; perhaps it would be enough to prettify the URL here: https://github.com/tlienart/Franklin.jl/blob/41289c895f0cf3d0c65f35061d69558e44b02972/src/manager/rss_generator.jl#L188 since that is the only thing a human would see/click on. Perhaps that is better?

**Comment by tlienart** [comment]
Yes that's true

**Pull request merged**
