### PR TITLE
[WIP] Adding a path var for a custom tag page.

### LINKED ISSUE #604: allow custom tag address
At the moment tags will be at `/tag/XXX`;  could be good to  offer the possibility for `/YYY/XXX` via a global var (e.g. if  people  want `/tags/` instead  of  `/tag/`

### PR DESCRIPTION
**Pull request by mcognetta**
This resolves #604 by allowing a user to set a `tag_page_path` variable in `config.md` which changes the page /tag/XXX to /YYY/XXX where YYY is given by the user. I open it now as a WIP to check that the code part of the change is correct before adding documentation/tests/etc.

TODO:
- add tests
- add to documentation

### CODE REVIEW

**Comment by tlienart** [comment]
Yes this is perfect thanks!

Did you need to add the resets to global var to get the tests to pass?

I'm travelling atm but will aim to merge asap, thanks again!

**Comment by mcognetta** [comment]
Yes, I found I needed to set them as otherwise the tag_page_path could not be found. I think that I can set them just once per file though, rather than on a test-by-test basis like I have now. I will experiment and see.

**Comment by mcognetta** [comment]
I reduced the number of calls to `def_GLOBAL_VARS!()` in the tests. It was sufficient to call it once at the start of the files in most cases.

**Comment by tlienart** [comment]
Reviewing now and will then merge

**Pull request merged**
